debug: false
server:
  port: 8081

spring:
  application:
    name: provider
  main:
    allow-bean-definition-overriding: true


#Dubbo 服务提供者配置
#dubbo:
    #application:
    #name: provider
    #registry:
    # zookeeper 注册中心地址
    #address: zookeeper://192.168.124.17:2181
    #timeout: 5000
    #protocol:
    #name: dubbo
    #port: 20880