debug: false
server:
  port: 8081

spring:
  application:
    name: provider
  main:
    allow-bean-definition-overriding: true


#Dubbo 服务提供者配置
dubbo:
    application:
      name: provider
    registry:
      address: 192.168.124.25
      timeout: 5000
      port: 2181
      protocol: zookeeper
    protocol:
      name: dubbo
      port: 20880