#Dubbo 服务提供者配置
spring:
  application:
    name: provider
server:
  port: 8081


dubbo:
  application:
    name: provider
  registry:
    # zookeeper 注册中心地址
    address: zookeeper://127.0.0.1:2181
    timeout: 5000
  protocol:
    name: dubbo
    # dubbo端口
    port: 20880
debug: false